{% set version = "0.3.1" %}
{% set arm_variant_type = "sbsa" %}

package:
  name: libnvpl-common-dev
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/nvpl/redist/nvpl_common/linux-sbsa/nvpl_common-linux-sbsa-{{ version }}-archive.tar.xz
  sha256: 8a516d983a5e6ddc299aacaccc7992c3028e1abbd020a47ffcdb0219187e41b6

build:
  number: 1
  noarch: generic
  script:
    - cp -rv lib $PREFIX

requirements:
  host:
    - _nvpl_dev_mutex
  run:
    - {{ pin_compatible('_nvpl_dev_mutex', exact=True) }}
    - __unix

test:
  commands:
    - test -f $PREFIX/lib/cmake/nvpl/nvpl-config.cmake
    - test -f $PREFIX/lib/cmake/nvpl_common/nvpl_common-config.cmake

about:
  home: https://developer.nvidia.com/nvpl
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/nvpl/license.html
  summary: >-
    The NVIDIA Performance Libraries (NVPL) are a collection of high
    performance mathematical libraries optimized for the NVIDIA Grace Armv9.0
    architecture.
  description: >-
    The NVIDIA Performance Libraries (NVPL) are a collection of high
    performance mathematical libraries optimized for the NVIDIA Grace Armv9.0
    architecture.

    These CPU-only libraries have no dependencies on CUDA or CTK, and are drop
    in replacements for standard C and Fortran mathematical APIs allowing HPC
    applications to achieve maximum performance on the Grace platform.
  doc_url: https://docs.nvidia.com/nvpl/

extra:
  feedstock-name: libnvpl-common
  recipe-maintainers:
    - conda-forge/cuda
