github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  check_solvable: true
  version_updates:
    nvidia:
      compute_subdir: nvpl
      json_name: nvpl_common
